"""Seed script — populates the database with 10 LLM trading cards."""

from .extensions import db
from .models import Card

CARDS_DATA = [
    {
        'name': 'DeepSeek V4',
        'slug': 'deepseek-v4',
        'mascot_name': 'Abyssal',
        'mascot_description': (
            'Born in the crushing depths of the Mariana Trench of data, '
            'Abyssal is an anglerfish dragon whose bioluminescent lure draws '
            'knowledge from the darkest corners of the internet. Its indigo '
            'scales shimmer with encoded wisdom.'
        ),
        'mascot_image': '/mascots/deepseek-v4.png',
        'color_primary': '#0d1b4a',
        'color_secondary': '#00e5ff',
        'parameters': 1600,
        'context_window': 1000,
        'benchmark_score': 95,
        'speed': 60,
        'community_score': 85,
        'openness': 95,
        'organization': 'DeepSeek',
        'license': 'MIT',
        'release_year': 2026,
        'tagline': 'From the abyss, infinite knowledge rises.',
    },
    {
        'name': 'GLM-5.1',
        'slug': 'glm-5-1',
        'mascot_name': 'Prismox',
        'mascot_description': (
            'Prismox is a crystalline fox forged from pure light refraction. '
            'Each facet of its body splits incoming queries into spectral '
            'solutions. It sees problems from every angle simultaneously.'
        ),
        'mascot_image': '/mascots/glm-5-1.png',
        'color_primary': '#2d1b69',
        'color_secondary': '#ff6bff',
        'parameters': 744,
        'context_window': 512,
        'benchmark_score': 93,
        'speed': 55,
        'community_score': 70,
        'openness': 90,
        'organization': 'Zhipu AI',
        'license': 'MIT',
        'release_year': 2026,
        'tagline': 'Every problem refracts into a thousand solutions.',
    },
    {
        'name': 'Kimi K2.6',
        'slug': 'kimi-k2-6',
        'mascot_name': 'Lunara',
        'mascot_description': (
            'Lunara leaps between moonbeams, her crescent antlers channeling '
            'lunar tides of computation. Patient and relentless, she runs '
            'through the longest reasoning chains without ever losing her way.'
        ),
        'mascot_image': '/mascots/kimi-k2-6.png',
        'color_primary': '#1a1a3e',
        'color_secondary': '#c084fc',
        'parameters': 400,
        'context_window': 1000,
        'benchmark_score': 88,
        'speed': 65,
        'community_score': 60,
        'openness': 75,
        'organization': 'Moonshot AI',
        'license': 'Modified MIT',
        'release_year': 2026,
        'tagline': 'By moonlight, the longest paths become clear.',
    },
    {
        'name': 'Qwen 3.6',
        'slug': 'qwen-3-6',
        'mascot_name': 'Zephyra',
        'mascot_description': (
            'Zephyra is a wind-spirit phoenix, her jade-and-gold plumage '
            'trailing cloud wisps across every language on Earth. She speaks '
            'them all — fluently, beautifully, and fast.'
        ),
        'mascot_image': '/mascots/qwen-3-6.png',
        'color_primary': '#0a3d2e',
        'color_secondary': '#34d399',
        'parameters': 235,
        'context_window': 128,
        'benchmark_score': 85,
        'speed': 90,
        'community_score': 88,
        'openness': 92,
        'organization': 'Alibaba',
        'license': 'Apache 2.0',
        'release_year': 2026,
        'tagline': 'The winds carry words in every tongue.',
    },
    {
        'name': 'Llama 4 Maverick',
        'slug': 'llama-4-maverick',
        'mascot_name': 'Valcuno',
        'mascot_description': (
            'Valcuno stands defiant atop a volcanic ridge, obsidian armor '
            'cracked with molten orange light. The mightiest of the open-weight '
            'herd, it charges into battle with an ecosystem of millions behind it.'
        ),
        'mascot_image': '/mascots/llama-4-maverick.png',
        'color_primary': '#3b0a0a',
        'color_secondary': '#f97316',
        'parameters': 400,
        'context_window': 1024,
        'benchmark_score': 87,
        'speed': 70,
        'community_score': 98,
        'openness': 65,
        'organization': 'Meta',
        'license': 'Community',
        'release_year': 2025,
        'tagline': 'From the forge of the open herd, a maverick rises.',
    },
    {
        'name': 'Gemma 4',
        'slug': 'gemma-4',
        'mascot_name': 'Crystara',
        'mascot_description': (
            'Crystara perches silently on a branch of living circuitry, her '
            'diamond eyes cutting through complexity with surgical precision. '
            'Small but devastatingly efficient — a gem among giants.'
        ),
        'mascot_image': '/mascots/gemma-4.png',
        'color_primary': '#1e1b4b',
        'color_secondary': '#818cf8',
        'parameters': 27,
        'context_window': 128,
        'benchmark_score': 78,
        'speed': 95,
        'community_score': 80,
        'openness': 95,
        'organization': 'Google',
        'license': 'Apache 2.0',
        'release_year': 2026,
        'tagline': 'Brilliance compressed into a single gem.',
    },
    {
        'name': 'Mistral Small 4',
        'slug': 'mistral-small-4',
        'mascot_name': 'Borealys',
        'mascot_description': (
            'Borealys prowls the frozen tundra, aurora borealis rippling '
            'through its fur in waves of green, purple, and blue. Its icy '
            'breath carries whispers of structured function calls.'
        ),
        'mascot_image': '/mascots/mistral-small-4.png',
        'color_primary': '#0c2340',
        'color_secondary': '#38bdf8',
        'parameters': 24,
        'context_window': 128,
        'benchmark_score': 76,
        'speed': 92,
        'community_score': 75,
        'openness': 85,
        'organization': 'Mistral AI',
        'license': 'Apache 2.0',
        'release_year': 2025,
        'tagline': 'Cold precision, northern beauty.',
    },
    {
        'name': 'Phi-4-mini',
        'slug': 'phi-4-mini',
        'mascot_name': 'Quarky',
        'mascot_description': (
            'Quarky is impossibly small yet impossibly powerful — a quantum '
            'sprite whose electron-orbit rings hum with compressed reasoning. '
            'Proof that size is just a number.'
        ),
        'mascot_image': '/mascots/phi-4-mini.png',
        'color_primary': '#1a1a2e',
        'color_secondary': '#e879f9',
        'parameters': 3.8,
        'context_window': 16,
        'benchmark_score': 65,
        'speed': 99,
        'community_score': 70,
        'openness': 90,
        'organization': 'Microsoft',
        'license': 'MIT',
        'release_year': 2025,
        'tagline': 'Small particle. Massive impact.',
    },
    {
        'name': 'MiniMax M3',
        'slug': 'minimax-m3',
        'mascot_name': 'Cosmox',
        'mascot_description': (
            'Cosmox drifts through interstellar clouds, its galaxy-swirl fur '
            'containing entire constellations. Star-cluster whiskers twitch '
            'as it processes the multimodal universe.'
        ),
        'mascot_image': '/mascots/minimax-m3.png',
        'color_primary': '#0f172a',
        'color_secondary': '#fb923c',
        'parameters': 456,
        'context_window': 1000,
        'benchmark_score': 86,
        'speed': 58,
        'community_score': 50,
        'openness': 70,
        'organization': 'MiniMax',
        'license': 'Open Weights',
        'release_year': 2026,
        'tagline': 'The cosmos speaks in every modality.',
    },
    {
        'name': 'Command R+',
        'slug': 'command-r-plus',
        'mascot_name': 'Corsair',
        'mascot_description': (
            'Corsair is a parrot-cyborg adventurer, one brass telescope eye '
            'scanning the horizon for the best retrieval targets. Its '
            'compass-rose wings navigate RAG seas with swashbuckling confidence.'
        ),
        'mascot_image': '/mascots/command-r-plus.png',
        'color_primary': '#1c1917',
        'color_secondary': '#fbbf24',
        'parameters': 104,
        'context_window': 128,
        'benchmark_score': 74,
        'speed': 80,
        'community_score': 72,
        'openness': 88,
        'organization': 'Cohere',
        'license': 'CC-BY-NC',
        'release_year': 2025,
        'tagline': 'Adventure awaits in the retrieval seas.',
    },
    {
        'name': 'Llama 3.1 405B',
        'slug': 'llama-3-1-405b',
        'mascot_name': 'Titanus',
        'mascot_description': 'Titanus is a colossal, multi-armed ancient stone golem giant forged from cracked obsidian, holding glowing magical scrolls of knowledge.',
        'mascot_image': '/mascots/llama-3-1-405b.png',
        'color_primary': '#064e3b',
        'color_secondary': '#facc15',
        'parameters': 405,
        'context_window': 128,
        'benchmark_score': 89,
        'speed': 40,
        'community_score': 95,
        'openness': 65,
        'organization': 'Meta',
        'license': 'Community',
        'release_year': 2024,
        'tagline': 'The colossal titan of the open-weight world.',
    },
    {
        'name': 'Mixtral 8x22B',
        'slug': 'mixtral-8x22b',
        'mascot_name': 'Hydrax',
        'mascot_description': 'Hydrax is an eight-headed hydra dragon made of swirling storm clouds and lightning bolts, representing a powerful mixture of experts.',
        'mascot_image': '/mascots/mixtral-8x22b.png',
        'color_primary': '#312e81',
        'color_secondary': '#60a5fa',
        'parameters': 141,
        'context_window': 64,
        'benchmark_score': 82,
        'speed': 75,
        'community_score': 90,
        'openness': 85,
        'organization': 'Mistral AI',
        'license': 'Apache 2.0',
        'release_year': 2024,
        'tagline': 'Eight heads are better than one.',
    },
    {
        'name': 'DBRX',
        'slug': 'dbrx',
        'mascot_name': 'Brickster',
        'mascot_description': 'Brickster is a massive cybernetic golem constructed entirely of floating, interconnected glowing data blocks and neon bricks.',
        'mascot_image': '/mascots/dbrx.png',
        'color_primary': '#7f1d1d',
        'color_secondary': '#fca5a5',
        'parameters': 132,
        'context_window': 32,
        'benchmark_score': 80,
        'speed': 85,
        'community_score': 70,
        'openness': 85,
        'organization': 'Databricks',
        'license': 'Open Data',
        'release_year': 2024,
        'tagline': 'Built block by data block.',
    },
    {
        'name': 'Grok-1',
        'slug': 'grok-1',
        'mascot_name': 'Sarcasbot',
        'mascot_description': 'Sarcasbot is a sleek, chrome-plated futuristic robot with a perpetual digital smirk, juggling glowing holographic question marks.',
        'mascot_image': '/mascots/grok-1.png',
        'color_primary': '#020617',
        'color_secondary': '#94a3b8',
        'parameters': 314,
        'context_window': 8,
        'benchmark_score': 70,
        'speed': 60,
        'community_score': 80,
        'openness': 90,
        'organization': 'xAI',
        'license': 'Apache 2.0',
        'release_year': 2024,
        'tagline': 'Answers your questions, but with a smirk.',
    },
    {
        'name': 'Jamba 1.5 Large',
        'slug': 'jamba-1-5',
        'mascot_name': 'Mambara',
        'mascot_description': 'Mambara is a vibrant, neon green mamba snake with infinite looping scales, symbolizing the Mamba architecture and an emerald aura.',
        'mascot_image': '/mascots/jamba-1-5.png',
        'color_primary': '#065f46',
        'color_secondary': '#a7f3d0',
        'parameters': 398,
        'context_window': 256,
        'benchmark_score': 81,
        'speed': 88,
        'community_score': 65,
        'openness': 85,
        'organization': 'AI21 Labs',
        'license': 'Open Weights',
        'release_year': 2024,
        'tagline': 'Infinite context, serpentine grace.',
    },
    {
        'name': 'OLMo 2',
        'slug': 'olmo-2',
        'mascot_name': 'OpenOwl',
        'mascot_description': 'OpenOwl is a wise, fully transparent glass owl whose inner workings, cogs, and glowing blue data flows are entirely visible.',
        'mascot_image': '/mascots/olmo-2.png',
        'color_primary': '#172554',
        'color_secondary': '#93c5fd',
        'parameters': 13,
        'context_window': 4,
        'benchmark_score': 75,
        'speed': 95,
        'community_score': 85,
        'openness': 100,
        'organization': 'Allen AI',
        'license': 'Apache 2.0',
        'release_year': 2024,
        'tagline': 'Fully transparent, open to the core.',
    },
    {
        'name': 'Yi 34B',
        'slug': 'yi-34b',
        'mascot_name': 'Yin-Yang',
        'mascot_description': 'Yin-Yang is a perfectly balanced, ethereal twin-tailed dragon weaving between glowing binary 0s and 1s, silver and gold.',
        'mascot_image': '/mascots/yi-34b.png',
        'color_primary': '#4c1d95',
        'color_secondary': '#c4b5fd',
        'parameters': 34,
        'context_window': 200,
        'benchmark_score': 78,
        'speed': 90,
        'community_score': 75,
        'openness': 90,
        'organization': '01.AI',
        'license': 'Apache 2.0',
        'release_year': 2024,
        'tagline': 'Bilingual brilliance in perfect balance.',
    },
    {
        'name': 'Nemotron-4 340B',
        'slug': 'nemotron-4-340b',
        'mascot_name': 'GPU-Rex',
        'mascot_description': 'GPU-Rex is a terrifyingly awesome cybernetic T-Rex powered by a glowing green heart of stacked GPUs, with metallic scales.',
        'mascot_image': '/mascots/nemotron-4-340b.png',
        'color_primary': '#14532d',
        'color_secondary': '#86efac',
        'parameters': 340,
        'context_window': 4,
        'benchmark_score': 85,
        'speed': 50,
        'community_score': 60,
        'openness': 80,
        'organization': 'Nvidia',
        'license': 'Open Model',
        'release_year': 2024,
        'tagline': 'A dinosaur powered by pure compute.',
    },
    {
        'name': 'Falcon 180B',
        'slug': 'falcon-180b',
        'mascot_name': 'Aeris',
        'mascot_description': 'Aeris is a majestic, golden cyber-falcon soaring through streams of binary code with a piercing gaze and metallic feathers.',
        'mascot_image': '/mascots/falcon-180b.png',
        'color_primary': '#78350f',
        'color_secondary': '#fde047',
        'parameters': 180,
        'context_window': 2,
        'benchmark_score': 75,
        'speed': 55,
        'community_score': 70,
        'openness': 85,
        'organization': 'TII',
        'license': 'Falcon License',
        'release_year': 2023,
        'tagline': 'Soaring high above the open-source skies.',
    },
    {
        'name': 'Aya Expanse',
        'slug': 'aya-expanse',
        'mascot_name': 'Polyglot',
        'mascot_description': 'Polyglot is a beautiful chimera composed of elements from different global myths, representing its massive multilingual capabilities.',
        'mascot_image': '/mascots/aya-expanse.png',
        'color_primary': '#831843',
        'color_secondary': '#f9a8d4',
        'parameters': 32,
        'context_window': 8,
        'benchmark_score': 80,
        'speed': 85,
        'community_score': 88,
        'openness': 88,
        'organization': 'Cohere For AI',
        'license': 'CC-BY-NC',
        'release_year': 2024,
        'tagline': 'Connecting the world, one language at a time.',
    },
    {
        'name': 'Gemma 2 27B',
        'slug': 'gemma-2-27b',
        'mascot_name': 'Crystara Prime',
        'mascot_description': 'Crystara Prime is an evolved, highly polished crystalline golem with sharp, brilliant edges and a heart of compressed logic.',
        'mascot_image': '/mascots/gemma-2-27b.png',
        'color_primary': '#312e81',
        'color_secondary': '#a5b4fc',
        'parameters': 27,
        'context_window': 8,
        'benchmark_score': 84,
        'speed': 88,
        'community_score': 85,
        'openness': 95,
        'organization': 'Google',
        'license': 'Gemma License',
        'release_year': 2024,
        'tagline': 'The prime gem of the open collection.',
    },
    {
        'name': 'DeepSeek Coder V2',
        'slug': 'deepseek-coder-v2',
        'mascot_name': 'CodeKraken',
        'mascot_description': 'CodeKraken is a deep-sea kraken whose tentacles are made of glowing code strings typing simultaneously on floating holographic keyboards.',
        'mascot_image': '/mascots/deepseek-coder-v2.png',
        'color_primary': '#0f172a',
        'color_secondary': '#38bdf8',
        'parameters': 236,
        'context_window': 128,
        'benchmark_score': 86,
        'speed': 80,
        'community_score': 82,
        'openness': 95,
        'organization': 'DeepSeek',
        'license': 'MIT',
        'release_year': 2024,
        'tagline': 'Unleash the kraken on your codebase.',
    },
]


def seed_db():
    """Clear existing cards and insert the 22 LLM trading cards."""
    Card.query.delete()
    for data in CARDS_DATA:
        card = Card(**data)
        db.session.add(card)
    db.session.commit()
